### ISSUE TITLE
Monaco Editorを使用したcode synthax highlightの実装

### ISSUE THREAD

**Issue by inokawa** [n-inokawa/n-inokawa.github.io#31]
## 概要
#9 

## 対応内容
- 実現可能か調査
- 可能なら実装

**Comment by inokawa** [comment]
https://stackoverflow.com/questions/52700307/how-to-use-monaco-editor-for-syntax-highlighting
https://dev.to/swyx/how-to-add-monaco-editor-to-a-next-js-app-ha3
https://github.com/microsoft/monaco-editor/blob/master/docs/integrate-esm.md
https://qiita.com/mizchi/items/5c5cb5abcb22d87f9031
https://medium.com/@amazzal.elhabib/create-a-custom-web-editor-using-typescript-react-antlr-and-monaco-editor-part-1-2f710c69c18c

**Comment by inokawa** [comment]
https://github.com/microsoft/monaco-editor/issues/420
https://github.com/microsoft/monaco-editor/issues/438

**Comment by inokawa** [comment]
https://github.com/inokawa/monaco-editor-node

**Comment by grishy** [comment]
Great, thx!
